version: '3.8'

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile  # Looks for Dockerfile inside the db/ directory
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  fastapi:
    build:
      context: ./fastAPI
      dockerfile: Dockerfile  # Looks for Dockerfile inside the fastapi/ directory
    container_name: fastapi_container
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://myuser:mypassword@db/auth_db
    ports:
      - "8000:8000"
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
